encyclopedia/urls.py
from django.urls import path

from . import views

app_name = 'wiki'
urlpatterns = [
    path("random/", views.random, name="random"),
    path("save_edit/<str:entry>", views.save_edit, name="save_edit"),
    path("edit/<str:entry>/", views.edit, name="edit"),
    path("new/", views.new, name="new"),
    path("wiki/<str:entry>", views.entry, name="entry"),
    path("search/", views.search, name="search"),
    path("", views.index, name="index")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from markdown2 import markdown
from django import forms
from . import util
from random import randint

class SearchForm(forms.Form):
    search = forms.CharField(label="Search", required= False)
    widget = forms.Textarea(attrs={'placeholder':'Search Encyclopedia'})

class NewEntryForm(forms.Form):
    title = forms.CharField(label="Title", required=True)
    content = forms.CharField(label="Content", widget=forms.Textarea(attrs={'placeholder':'Enter markdown content'}))

class EditForm(forms.Form):
    title = forms.CharField(label="")
    content = forms.CharField(label="", widget=forms.Textarea)



def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def entry(request, entry):
    page = util.get_entry(entry)
    if page is None:
        return render(request, "encyclopedia/entry.html", {
        "entry": "Does not exist"
    })
    
    page = markdown(page)
    return render(request, "encyclopedia/entry.html", {
        "entry": entry,
        "content": page
    })

def search(request):
    query = request.GET['q']
    if util.get_entry(query):
        return HttpResponseRedirect(reverse("wiki:entry", args=(query,)))
    elif not util.get_entry(query):
        entries = util.list_entries()
        matches = []
        for entry in entries:
            if query in entry:
                matches.append(entry)

        if len(matches) != 0:
            return render(request, "encyclopedia/index.html", {
            "entries": matches
        })
        else:
            matches = ["No matches found"]
            return render(request, "encyclopedia/noResults.html", {
        "entries": matches
    })

        
    else:
        return render(request, "encyclopedia/error.html", {
        "error": "Page Does Not Exist",
        "text": "Please create a page for new users"
    })

def new(request):
    if request.method == "POST":
        form = NewEntryForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]

            entries = util.list_entries()
            if title in entries:
                return render(request, "encyclopedia/error.html", {
                    "error": "Entry Exists",
                    "text": "Please edit the entry through it's page"
                })

            else:
                markdown_title = "#" + title
                new_content = markdown_title + "\n" + content
                util.save_entry(title, new_content)
                entry = util.get_entry(title)
                page = markdown(entry)
                return render(request, "encyclopedia/entry.html", {
                "entry": title,
                "content": page
                })

    else:
        return render(request, "encyclopedia/new.html", {
            "form": NewEntryForm()
        })

def edit(request, entry):
    if request.method == 'GET':
        page = util.get_entry(entry)

        information  = {
            'edit': EditForm(initial={'content': page, 'title':entry}),
        }
        return render(request, "encyclopedia/edit.html", information)

    

def save_edit(request, entry):
    if request.method == 'POST':
        print("post valid")
        form = EditForm(request.POST)
        print("form recieved")
        content = request.POST.get("content", "").strip()
        title = request.POST.get("title", "").strip()
        print(content)
        print(title)

        util.save_entry(title, content)
        entry = util.get_entry(title)
        page = markdown(entry)
        return render(request, "encyclopedia/entry.html", {
        "entry": title,
        "content": page
        })

    else:
        return render(request, "encyclopedia/error.html", {
                    "error": "Error",
                    "text": "Your Submission Couldn't be Saved.  Please go back."
                })

def random(request):
    entries = util.list_entries()
    rangeInt = len(entries)-1
    number = randint(0,rangeInt)
    print(entries[number])
    randEntry = entries[number]
    entry = util.get_entry(randEntry)
    page = markdown(entry)
    return render(request, "encyclopedia/entry.html", {
    "entry": randEntry,
    "content": page
    })
    

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit Entry
{% endblock %}

{% block body %}
    <h1>Edit Entry<h1>
        <p style="font-weight: lighter; font-size: medium;">Please note that by changing the name of the entry it will create a new entry instead of editing the entry. <br> Also, please maintain all entries in markdown format (<a href="https://www.markdownguide.org/basic-syntax/">learn more here</a>) </p>
    <form action="{% url 'wiki:save_edit' edit.title %}" method="post">
        <label>Entry Name</label>
        {% for part in edit %}
            <div>
                {{part}} <br>
            </div>
        {% endfor %}


        {% csrf_token %}
        <input type="submit">
    </form>

    <a href="{% url 'wiki:index' %}">Return to Main</a>

{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}
{{ import markdown }
{% block title %}
   Wiki: {{entry}}
{% endblock %}

{% block body %}

{{ content|safe }}



<a href="{% url 'wiki:edit' entry %}"> Edit This Page </a>
<br>
<a href="{% url 'wiki:index' %}">Return to Main</a>

{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}
{% block title %}
   Error
{% endblock %}

{% block body %}
    <h1>{{error}}</h1>
    <p>{{text}}</p>

    <a href="{% url 'wiki:index' %}">Return to Main</a>


{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li> <a href="wiki/{{entry}}">{{ entry }} </a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'wiki:search' %}">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                   <a href="{% url 'wiki:new' %}"> Create New Page </a> 
                </div>
                <div>
                    <a href="{% url 'wiki:random' %}">Random Page</a> 
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/new.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    New Entry
{% endblock %}

{% block body %}
    <h1>Add A New Entry</h1>
    <h6>Please add all entries in markdown format (<a href="https://www.markdownguide.org/basic-syntax/">learn more here</a>)</h6>
    <form action="{% url 'wiki:new' %}" method="POST" id="NewEntryForm" style="width: 80%; display: block; font-weight: bolder;">
        {% csrf_token %}
        {% for part in form %}
            <div>
                {{part.label}} <br> {{part}} <br>
            </div>
        {% endfor %}
        <input type="submit" value="Submit">
    </form>

    <a href="{% url 'wiki:index' %}">Return to Main</a>

{% endblock %}

encyclopedia/templates/encyclopedia/noResults.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li> {{ entry }} </li>
        {% endfor %}
    </ul>

{% endblock %}